Jekyll fixes + testing changes
fsi-tue/skripte pull request #3
Opened 2018-03-22 16:04 UTC by primeos

Jekyll hat die CONTRIBUTING.md nicht gerendert: https://fsi-tue.github.io/skripte/CONTRIBUTING.md bzw. https://fsi-tue.github.io/skripte/CONTRIBUTING.html (404). Jetzt sieht es so aus: https://primeos.github.io/skripte/CONTRIBUTING.html. Ich hab auch gleich noch den Lizenz-Link gefixt und kurz dokumentiert, wie man die eigenen Änderungen testen kann (falls das jemand machen will).

2018-03-22 16:30 UTC, primeos commented
Der HTML-Proofer scheint grad nicht mehr richtig zu funktionieren... Nach dem Output werden evtl. die Zertifikate nicht mehr akzeptiert (falsche Zeit/Systemzertifikate, etc.).

2018-03-22 17:06 UTC, primeos commented
Jetzt sollte alles passen.

2018-03-23 09:49 UTC, Trybnetic commented
Danke dir!

Das Problem mit den SVG links hatte ich auch schonmal, wusste aber nicht, woran das liegt..
Wie bist du drauf gekommen, dass es an `libcurl4-openssl-dev` liegt?

2018-03-23 12:08 UTC, primeos commented
Weiß ich leider selber nicht mehr ganz genau, war jedenfalls etwas tricky...
Hab erst mal auf meinem eigenen Fork Travis CI aktiviert und ein paar Tests gemacht, wobei sich rausgestellt hat, das eigentlich alles passt (Systemzeit, /etc/ssl, etc.) und nachdem `curl` auch keine Probleme hatte ("SSL certificate verify ok.") hab ich mir mal das [html-proofer repo](https://github.com/gjtorikian/html-proofer) genauer angeschaut, wie die das intern machen. Am schlausten wäre es gewesen direkt nach der Fehlermeldung zu suchen, dann müsste man eigentlich gleich den Wiki-Eintrag dazu finden: https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis. Ich hab dann erst mal noch in's [Typhoeus repo](https://github.com/typhoeus/typhoeus) (Ruby libcurl wrapper) geschaut und da dann IIRC ein issue zu gefunden (vermutlich `https://github.com/typhoeus/typhoeus/issues/568`).

Jedenfalls hatte ich bei Travis CI eigentlich folgende Ausgabe für `curl --version`:
```
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```
Wo eigentlich `OpenSSL/1.0.1f` steht, aber zumindest `libcurl` linkt bei Ubuntu per default wohl gegen GnuTLS (hab ich dann aber nicht mehr mit `ldd` geprüft). Jedenfalls link `libcurl4-openssl-dev` dann gegen OpenSSL statt GnuTLS (mit so Sachen hatte ich bei Debian/Ubuntu schon öfters mal Probleme, die dependency resolution gefällt mir da teilweise noch nicht so ganz). Kanns mir auch nachher evtl. nochmal etwas genauer anschauen.

2018-03-23 13:55 UTC, primeos commented
Ok, noch kurz zum Fix:

Ein log mit ein paar Setup-Infos: https://travis-ci.org/primeos/skripte/builds/357380344

```console
$ dpkg -l | grep libcurl
ii  libcurl3:amd64                           7.35.0-1ubuntu2.13                         amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64                    7.35.0-1ubuntu2.13                         amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4-gnutls-dev:amd64                7.35.0-1ubuntu2.13                         amd64        development files and documentation for libcurl (GnuTLS flavour)
```

Default ist also `libcurl4-gnutls-dev`, aber `Typhoeus` kommt nicht mit den anderen return codes von GnuTLS klar.

Full "debug" log: https://travis-ci.org/primeos/skripte/builds/357395821

`htmlproofer` lädt: `/usr/lib/x86_64-linux-gnu/libcurl.so` (s. `strace`). Mit `libcurl4-openssl-dev` wird dann gegen OpenSSL (libssl) gelinkt, wodurch die return codes wieder stimmen (und aus Gründen(?) trotzdem zusätzlich noch gegen GnuTLS).

```console
$ ldd /usr/lib/x86_64-linux-gnu/libcurl.so
	linux-vdso.so.1 =>  (0x00007fff72b43000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f828a5de000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f828a3c4000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f828a144000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f8289e85000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f8289c3e000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f8289a2f000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f82897de000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f82895c5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82893a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8288fde000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f8288dd9000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f8288bc5000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f8288983000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f82886b8000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f8288489000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f8288285000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f828807a000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f8287e5f000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f8287c44000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f8287a06000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f828aa73000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f82877fe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f82875fa000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f82873f6000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f82871ed000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f8286f65000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f8286cc4000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f8286a91000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f828687c000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f8286653000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f8286445000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f82861fc000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f8285f43000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f8285d0a000)
$ sudo apt-get install --quiet --yes libcurl4-openssl-dev
The following additional packages will be installed:
  curl libcurl3
Suggested packages:
  libcurl4-doc libcurl3-dbg
The following packages will be REMOVED:
  libcurl4-gnutls-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev
The following packages will be upgraded:
  curl libcurl3
2 upgraded, 1 newly installed, 1 to remove and 160 not upgraded.
$ ldd /usr/lib/x86_64-linux-gnu/libcurl.so
	linux-vdso.so.1 =>  (0x00007fffe37fa000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f075c51e000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f075c304000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f075c0a5000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f075bcc9000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f075ba82000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f075b873000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f075b622000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f075b409000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f075b1eb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f075ae22000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f075ab63000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f075a8e3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f075a6df000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f075a414000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f075a1e5000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f0759fe1000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f0759dd6000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f0759bbb000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f07599a0000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f0759762000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f075c9b8000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f075954e000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f075930c000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f0759107000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f0758f03000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f0758cfa000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f0758a72000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f07587d1000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f075859e000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f0758389000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f0758181000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f0757f58000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f0757d4a000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f0757b01000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f0757848000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f075760f000)
```

2018-03-23 14:16 UTC, Trybnetic commented
Sehr cool, danke dir dafuer, dass du das rausgefunden hast! :+1:

2018-03-23 14:18 UTC, Trybnetic requested changes
Ersteinmal nochmal vielen Dank fuer den PR!

Ein kleine Anmerkung hab ich allerdings noch ;-)

2018-03-23 14:18 UTC, Trybnetic commented on CONTRIBUTING.md
> +du deine Seite über https://&lt;user&gt;.github.io/skripte/ aufrufen. Alternativ
Da wir davor den Benutzernamen als `yourname` definiert haben (siehe Zeile 35) waere es denke gut, wenn wir das hier so beibehalten

2018-03-23 15:08 UTC, primeos commented on CONTRIBUTING.md
> +du deine Seite über https://&lt;user&gt;.github.io/skripte/ aufrufen. Alternativ
Danke, hatte ich wohl übersehen/vergessen...

2018-03-23 16:13 UTC, Trybnetic approved these changes

2018-03-23 16:14 UTC, merged